### ISSUE TITLE
AttributeError: 'module' object has no attribute 'And' (in net.py)

### ISSUE THREAD

**Issue by byt3bl33d3r** [the-useless-one/pywerview#16]
Heya, 
ran into this error when running `get-netgroupmemeber` and `get-netdomaincontroller`:

```
Traceback (most recent call last):
  File "/root/.virtualenvs/CME/bin/pywerview", line 11, in <module>
    load_entry_point('pywerview==0.1.1', 'console_scripts', 'pywerview')()
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/cli/main.py", line 342, in main
    results = args.func(**parsed_args)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/cli/helpers.py", line 128, in get_netgroupmember
    full_data=full_data, custom_filter=custom_filter)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/requester.py", line 126, in wrapper
    return f(*args, **kwargs)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/functions/net.py", line 364, in get_netgroupmember
    members = _get_members(groupname, sid)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/functions/net.py", line 304, in _get_members
    queried_sid = misc_requester.get_domainsid(queried_domain) + '-512'
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/functions/misc.py", line 65, in get_domainsid
    domain_controllers = r.get_netdomaincontroller(queried_domain=queried_domain)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/requester.py", line 126, in wrapper
    return f(*args, **kwargs)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/functions/net.py", line 142, in get_netdomaincontroller
    custom_filter=domain_controller_filter)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/requester.py", line 126, in wrapper
    return f(*args, **kwargs)
  File "/root/.virtualenvs/CME/lib/python2.7/site-packages/pywerview-0.1.1-py2.7.egg/pywerview/functions/net.py", line 109, in get_netcomputer
    computer_search_filter['and'] = ldapasn1.And()
AttributeError: 'module' object has no attribute 'And'
```

Cheers

**Comment by the-useless-one** [comment]
Thanks for the issue, I forgot to remove some legacy code. It should work now, let me know if there is any problem with the fix.

Cheers,

Y
