### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Greenwolf** [the-useless-one/pywerview#30]
Good Morning, 

I get the following error when running invoke-eventhunter

```
# python pywerview.py invoke-eventhunter -w domain.com -u domainadmin -p password -t 10.x.x.x --userfile target-users.txt --search-days 5

Process EventHunterWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/Desktop/pywerview/pywerview/worker/hunting.py", line 43, in run
    result = self._hunt(target_computer)
  File "/root/Desktop/pywerview/pywerview/worker/hunting.py", line 155, in _hunt
    for event in distant_events:
TypeError: 'NoneType' object is not iterable
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!

Sorry for the (extremely) late response but I think I fixed the issue, you can try it with this branch https://github.com/the-useless-one/pywerview/tree/fix_hunting

I'm closing now, feel free to re-open if needed.

:sunflower:
