### ISSUE TITLE
TypeError: __init__() takes 13 positional arguments but 14 were given

### ISSUE THREAD

**Issue by CaledoniaProject** [the-useless-one/pywerview#59]
--computerfile results in argument error

```
Traceback (most recent call last):
  File "pywerview.py", line 23, in <module>
    main()
  File "/root/pywerview-master/pywerview/cli/main.py", line 578, in main
    results = args.func(**parsed_args)
  File "/root/pywerview-master/pywerview/cli/helpers.py", line 329, in invoke_userhunter
    foreign_users=foreign_users)
  File "/root/pywerview-master/pywerview/functions/hunting.py", line 211, in invoke_userhunter
    domain_short_name, check_access))
  File "/root/pywerview-master/pywerview/functions/hunting.py", line 142, in _build_workers
    self._do_kerberos, self._do_tls, *worker_args)
TypeError: __init__() takes 13 positional arguments but 14 were given
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,

Can you try my fix on this branch: https://github.com/the-useless-one/pywerview/tree/fix_hunting ? Thanks

:sunflower: 


EDIT: fix the branch name

**Comment by CaledoniaProject** [comment]
New problems

```
Traceback (most recent call last):
  File "/xxx/pywerview/./pywerview.py", line 23, in <module>
    main()
  File "/xxx/pywerview/pywerview/cli/main.py", line 606, in main
    and not args.user_cert is None and args.user_key is None):
AttributeError: 'Namespace' object has no attribute 'user_cert'
```

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!

I fixed the user hunting function, can you check the branch https://github.com/the-useless-one/pywerview/tree/fix_hunting ? Thanks

:sunflower:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I tested the fix during a engagement, it works.
Closing now.

:sunflower:
